### PR TITLE
Adding notes

### PR DESCRIPTION
**Pull request by 1beb**
Hi @paciorek

This refs #8 also added a section about process design as I felt it was pertinent and something I had to experiment with before understanding completely. 

I'm not sure about what you would prefer where. Some cross-referencing to other elements of your repositories may also be necessary. Alternatively it may be prudent to bring all of the different pieces into one repository (future-helm, future-kubernetes, and the dockerfile all under one roof). I found this to be most useful for iteration, personally.

### CODE REVIEW

**Comment by 1beb** [comment]
@paciorek bump

**Comment by paciorek** [comment]
Thanks for the reminder. I may not get to this for a few weeks however given some summer travel.

**Comment by paciorek** [comment]
@1beb Just looking finally at your design/topologies doc. Are you sure that if one requests `n` GKE virtual machines, each with `c` cores, and then you ask for `n` pods in your Helm chart that each of those pods can actually access multiple cores? 

Assuming so, I am worried about confusing folks with the nested futures, compared to the single layer that I present. I guess I could preface your text with a note about having a single future compared to nested futures.

**Comment by 1beb** [comment]
Now that I go back, I think I need to make some adjustments because the second plan specification wasn't necessary. `future` automatically understood how to use the worker's cores with the nested futures with just the cluster plan, excluding the nested multisession. 

One problem in general that I'm running into "in real life" that I think is still a mystery to me is OOMkills when I scale to anything past the number of scheduler cores. I'd like to get that solved before merging this as I feel like the whole purpose of kubernetes is lost if you can't scale your process to n = 50, n = 100, n = 1000 ans so on. I'm not sure how to report that error, I don't know how "minimal" a reproducible example would be (given the cost associated with scaling). 

In the interim, if you'd like to chop up the notes here and exclude the future topologies section I think you could place them, reasonably, in other places.

**Comment by paciorek** [comment]
@1beb I finally got back to look at this more. At this point, my thought would be to add a link to the secrets/ecr document in a new section "Additional information" that I would add to the README and note at the top of the secrets/ecr document that you are the author.

How does that sound?

**Comment by 1beb** [comment]
Hi @paciorek feel free to chop up the pieces that you feel are right for the repo. Attribution would be nice, but is not necessary! Thanks!

**Comment by paciorek** [comment]
Ok, I added the secrets/ECR info in. Thanks, @1beb !

I'm closing this for now, but feel free to re-open for further discussion.

**Pull request closed without merging**
